apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: exampleapp
        image: gcr.io/mana-ysh-2020/exampleapp:latest
        imagePullPolicy: Always