# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}   # TODO: update to cluster name
  GKE_ZONE: asia-northeast1-a  # TODO: update to cluster zone
  ENVIRONMENT: gcp

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest mypy pytest-cov
        pip install .
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Type checking
      run: |
        make typecheck
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    # Configure GCP (docker and GKE)
    - run: |-
        make init-gcp GKE_CLUSTER=$GKE_CLUSTER GKE_ZONE=$GKE_ZONE
    # build docker image
    - run: |-
        make build-image
    # push the Docker image
    - name: push
      run: |-
        make push-image PROJECT_ID=$PROJECT_ID TAG=${TAG}
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    - name: Deploy
      run: |-
        make deploy ENVIRONMENT=$ENVIRONMENT TAG=${TAG}